"""Recurrence engine for JSCalendar 2.0 (Section 3.3).

Expands the recurrence set of an Event or Task: the initial date-time, the
date-times generated by "recurrenceRule" (Section 3.3.3.1), and the
occurrences added, excluded, or modified by "recurrenceOverrides"
(Section 3.3.4), yielded as :class:`Occurrence` instances in recurrence id
order.
"""

from __future__ import annotations

from collections.abc import Iterator, Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime
from typing import Any

from json_calendar.models import Event, Task
from json_calendar.models.calendar_object import occurrence_json
from json_calendar.recurrence._rule import UnsupportedCalendarError, iterate

__all__ = ["Occurrence", "UnsupportedCalendarError", "expand"]


@dataclass(frozen=True)
class Occurrence:
    """One occurrence of a (possibly recurring) Event or Task.

    ``recurrence_id`` is the occurrence's key in the recurrence set, and
    ``start`` its effective start — for a Task with no start, its due —
    date-time: the recurrence id unless a "recurrenceOverrides" patch (kept
    in ``patch``, None for unmodified rule occurrences) replaced it.
    """

    base: Event | Task
    recurrence_id: datetime
    start: datetime
    patch: Mapping[str, Any] | None = None

    def materialize(self) -> Event | Task:
        """This occurrence as a standalone instance object (Section 3.3.1).

        The instance inherits the base object's properties with the start
        (or due) date-time shifted to the recurrence id, the override patch
        applied, and "recurrenceId"/"recurrenceIdTimeZone" set
        (Section 3.3.4). If the base object already is an instance, or is
        not recurring at all — its single occurrence being the object
        itself — it is returned as-is.
        """
        if self.base.recurrenceId is not None:
            return self.base
        if self.base.recurrenceRule is None and not self.base.recurrenceOverrides:
            # Instances exist only of a recurring object (Section 3.3.1); a
            # synthetic "recurrenceId" here would also be invalid on a Task
            # with no "start" (Section 4.2).
            return self.base
        data = occurrence_json(self.base, self.recurrence_id, self.patch)
        return type(self.base).model_validate(data)


def expand(
    obj: Event | Task, *, start: datetime | None = None, end: datetime | None = None
) -> Iterator[Occurrence]:
    """Yield the occurrences of ``obj``, in recurrence id order.

    ``start`` (inclusive) and ``end`` (exclusive) bound the *effective*
    start date-times of the yielded occurrences; without an ``end`` the
    iterator over an unbounded rule is infinite. All date-times are local
    (Section 1.5.5), in the object's time zone.

    Raises UnsupportedCalendarError for rules with a non-Gregorian "rscale".
    """
    initial = obj.start if not isinstance(obj, Task) or obj.start is not None else obj.due
    if initial is None:  # an untimed Task has no occurrences
        return iter(())
    if obj.recurrenceId is not None:
        # Already a single instance of a recurring object (Section 3.3.1);
        # such objects have no rule or overrides of their own.
        occurrence = Occurrence(base=obj, recurrence_id=obj.recurrenceId, start=initial)
        in_window = (start is None or initial >= start) and (end is None or initial < end)
        return iter((occurrence,) if in_window else ())
    if obj.recurrenceRule is not None:
        rule_ids = iterate(obj.recurrenceRule, initial)  # raises for unsupported rscale
    else:
        rule_ids = iter((initial,))
    shifted = "due" if isinstance(obj, Task) and obj.start is None else "start"
    overrides = sorted((obj.recurrenceOverrides or {}).items())
    return _merge(obj, rule_ids, overrides, shifted, start, end)


def _merge(
    obj: Event | Task,
    rule_ids: Iterator[datetime],
    overrides: Sequence[tuple[datetime, Mapping[str, Any]]],
    shifted: str,
    start: datetime | None,
    end: datetime | None,
) -> Iterator[Occurrence]:
    """Merge the rule's date-times with the overrides, in recurrence id order.

    An override whose id matches a rule date-time modifies that occurrence;
    any other override adds one (Section 3.3.4). Past ``end``, the rule is
    only consumed as far as the last override id, whose patch might move
    its occurrence back into the window.
    """
    index = 0
    for recurrence_id in rule_ids:
        while index < len(overrides) and overrides[index][0] < recurrence_id:
            yield from _occurrence(obj, *overrides[index], shifted, start, end)
            index += 1
        patch = None
        if index < len(overrides) and overrides[index][0] == recurrence_id:
            patch = overrides[index][1]
            index += 1
        yield from _occurrence(obj, recurrence_id, patch, shifted, start, end)
        if end is not None and recurrence_id >= end and index >= len(overrides):
            return
    for recurrence_id, patch in overrides[index:]:
        yield from _occurrence(obj, recurrence_id, patch, shifted, start, end)


def _occurrence(
    obj: Event | Task,
    recurrence_id: datetime,
    patch: Mapping[str, Any] | None,
    shifted: str,
    start: datetime | None,
    end: datetime | None,
) -> Iterator[Occurrence]:
    """Yield the occurrence at ``recurrence_id`` if it falls in the window."""
    if patch is not None and "excluded" in patch:  # exactly {"excluded": true}
        return
    effective = recurrence_id
    if patch is not None and shifted in patch:
        # A patched start (or due) takes precedence over the recurrence id
        # (Section 3.3.4); the patch was validated with the base object.
        effective = datetime.fromisoformat(patch[shifted])
    if start is not None and effective < start:
        return
    if end is not None and effective >= end:
        return
    yield Occurrence(base=obj, recurrence_id=recurrence_id, start=effective, patch=patch)
